### ISSUE TITLE
Out of date template files

### ISSUE THREAD

**Issue by michael-77** [scottcmoore/p-g-wodehouse_psmith-in-the-city#1]
Since starting there have been a few updates to some of the template files.

If you run `git pull` on the tools directory then running `lint` again will suggest updating
> LICENSE.md
> core.css
> logo.svg
> uncopyright.xhtml

New versions can then be copied and pasted from the templates sub-directory in the tools.

**Comment by scottcmoore** [comment]
I ran `git pull` in the tools directory and re-ran lint, but lint didn't suggest any changes to those files. I also ran diff against the files and didn't see any differences. Am I missing something?

**Comment by michael-77** [comment]
My apologies - its newline only differences.
