### ISSUE TITLE
Missing Frontmatter

### ISSUE THREAD

**Issue by michael-77** [scottcmoore/p-g-wodehouse_psmith-in-the-city#2]
The original page scans include a dedication which should be included in a `dedication.xhtml` file.

It reads:

> To Leslie Havergal Bradshaw

The section https://standardebooks.org/contribute/semantics#epigraphs with reference to `epigraph` changed to `dedication` can be used to guide the production of that file and an example of a complete one is at https://github.com/standardebooks/bram-stoker_dracula/blob/master/src/epub/text/dedication.xhtml

There is also a preface (by PG Wodehouse) which is in earlier editions and should be included in a `preface.xhtml` file.  It would contain:
```
<p>Mike and Psmith first appeared in a book called <i epub:type="se:name.publication.book">Mike</i>. This story opens about a month after they have left school.</p>
<footer>
	<p class="signature"><abbr class="name">P. G.</abbr> Wodehouse</p>
</footer>
```
 as the main content there.

`<meta property="role" refines="#author" scheme="marc:relators">wpr</meta>` will need to be added as an extra line in content.opf to identify Wodehouse as author of the preface as well as the main work (or `lint` will complain).

A `halftitle.xhtml` needs to be included when frontmatter exists.  See https://github.com/standardebooks/john-meade-falkner_moonfleet/blob/master/src/epub/text/halftitle.xhtml for an example of what that looks like.

You'll then need to regenerate the `spine` and `manifest` in `content.opf` to take into account the extra files.

**Comment by scottcmoore** [comment]
I added the missing frontmatter, and updated content.opf, in the latest commit dd11a9f72ccccaa4e0211b852e88fa8508146923.

**Comment by michael-77** [comment]
The files haven't made it to github.
Need to add:
- preface.xhtml
- dedication.xhtml
- halftitle.xhtml

The references in the documents seem ok but `lint` won't run smoothly without those files and the build step will fail.  They won't show up locally as you'll have the files on your machine!

**Comment by scottcmoore** [comment]
🤦‍♂️ Added these files in c3311eebfa4aaaeabe708d6d3f8f0409ce596428

**Comment by michael-77** [comment]
Its all running clean on `lint` etc now.
