### ISSUE TITLE
Update to toc.xhtml

### ISSUE THREAD

**Issue by michael-77** [scottcmoore/p-g-wodehouse_psmith-in-the-city#3]
The Dedication, Preface and Halftitle need to be included and the main chapters nested within a secondary `<ol>` within the `<li>` containing the halftitle.

See https://github.com/standardebooks/john-meade-falkner_moonfleet/blob/master/src/epub/toc.xhtml for an example of how this nesting works in practice.

The Roman Numeral chapter numbers should be followed by a colon. ie
```
<a href="text/chapter-1.xhtml"><span epub:type="z3998:roman">I</span>: <abbr>Mr.</abbr> Bickersdyke Walks Behind the Bowler’s Arm</a>
```

The dedication, preface and halftitle need to be included in the landmarks at the bottom of that file as well.

**Comment by scottcmoore** [comment]
I updated the toc.xhtml in the latest commit dd11a9f72ccccaa4e0211b852e88fa8508146923

**Comment by michael-77** [comment]
[toc.xhtml](https://github.com/scottcmoore/p-g-wodehouse_psmith-in-the-city/blob/dd11a9f72ccccaa4e0211b852e88fa8508146923/src/epub/toc.xhtml) looks fine now.

Great stuff!
