### ISSUE TITLE
Abbreviations need marked up

### ISSUE THREAD

**Issue by michael-77** [scottcmoore/p-g-wodehouse_psmith-in-the-city#5]
In Chapter 22, `<span>etc.</span>` should be `<abbr>etc.</abbr>`

In `colophon.xhtml` "P. G." should be enclosed by `<abbr class="name">` tags, as should the "C." in "Scott C. Moore" and the "L." in "Suzanne L. Shell"

**Comment by scottcmoore** [comment]
Fixed in latest commit dd11a9f72ccccaa4e0211b852e88fa8508146923
