### ISSUE TITLE
Missing breaks

### ISSUE THREAD

**Issue by michael-77** [scottcmoore/p-g-wodehouse_psmith-in-the-city#6]
Gutenberg is quite bad for omitting breaks in the text.  

For example in chapter 1 there is a break in the page scans before the paragraph starting "It was during this week..." and this should be marked up with `<hr/>`.  

There may be others in the scans which are missing from the xhtml files and a scroll through the page scans would identify any missing ones.  

I found a Hathi Trust edition which is easier to scan through than the PGDP pages - https://catalog.hathitrust.org/Record/102499762.  

If you use this then you'll need to add it as an additional `dc:source` in content.opf and add the links to colophon.xhtml and imprint.xhtml.

**Comment by scottcmoore** [comment]
Thanks for finding that much easier-to-read edition! Really loved the illustrations in that one too. 

I added references to it in content.opf, colophon.xhtml, and imprint.xhtml as part of commit dd11a9f72ccccaa4e0211b852e88fa8508146923

I also added what I think are all the missing `<hr/>` tags.

**Comment by michael-77** [comment]
😃
