### ISSUE TITLE
Update to descriptions in content.opf

### ISSUE THREAD

**Issue by michael-77** [scottcmoore/p-g-wodehouse_psmith-in-the-city#7]
Short descriptions don't tend to use the names but describe the characters, say:

> A young man abandons his dream of playing cricket at Cambridge because of financial trouble and goes to work for a London bank, where he’s joined by an unflappable friend.

The long description as it stands is rather dependent on knowing about the prequel *Mike* - you could use the "Plot Introduction" from the Wikipedia page as a starting point and include a short paragraph about PG Wodehouse. 

I haven't read the book (yet) but something like this might be a little fuller:

> Mike Jackson is a rising cricket star who finds his dreams of studying and playing at Cambridge upset by news of his father's financial troubles.  He takes a job with the New Asiatic Bank in London. He arrives to find that his dapper and verbose young friend Psmith is also a new employee, and together they navigate early twentieth century office life, make the best of their position and squeeze in a little cricket from time to time.
>
> Sir Pelham Grenville Wodehouse was an English author and one of the most widely read humorists of the twentieth century. After leaving school, he was employed by a bank but disliked the work and turned to writing in his spare time. His early novels were mostly school stories, but he later switched to comic fiction, creating several regular characters who became familiar to the public over the years. 
>
> *Psmith in the City* was originally serialized in *The Captain* magazine in 1908 and 1909 as *The New Fold* and is the sequel to *Mike*, an earlier novel by Wodehouse.

**Comment by scottcmoore** [comment]
I feel like these descriptions are much better than what I could write. Is there any reason not to just use these as you've written them? Or should I take a second stab at it myself?

**Comment by michael-77** [comment]
Nothing to stop you using those 😄

**Comment by scottcmoore** [comment]
Great, I've updated content.opf with your descriptions in b83e03d67d100378c5291c98c44c9248bd50345f
Thanks!

**Comment by michael-77** [comment]
No problems.  I struggle with descriptions as well.
